import Footer from "@components/Footer";
import Input from "@components/Input";
import Button from "@components/Button";
import Card from "@components/Card";
import Link from "next/link";
import Head from "next/head";
import { useState, useEffect } from 'react';
import axios from "axios";
import { useRouter } from "next/router";

function Login() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const router = useRouter();

    const login = () => {
        axios.post('http://103.150.60.157:6969/v1/admin/login', {
            password,
            email,
        }).then(res => {
            console.log(res);
            router.push("./dashboard");
        }).catch(err => {
            console.log(`message : ${err}`);
        })
    }

    return (
        <div className="h-screen bg-primary text-white overflow-hidden flex flex-col">
            <Head>
                <title>Toqcer | login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex-1 flex flex-col items-center">
                <h1 className="text-orange font-bold text-4xl my-14">ToqCer</h1>
                {/* Form */}
                <div className="max-w-md w-full">
                    <Card title="Sign In">
                        <Input
                            label="email"
                            placeholder="Email"
                            type="email"
                            onChange={e => setEmail(e.target.value)} />
                        <Input
                            label="password"
                            placeholder="Password"
                            type="password"
                            onChange={e => setPassword(e.target.value)} />
                        <Button onClick={login}>Sign in</Button>
                    </Card>
                    <div className="flex justify-between text-sm px-2 py-3 text-muted ">
                        <Link href='#forgot' passHref>
                            <a className="hover:text-white">Forgot password ?</a>
                        </Link>
                    </div>
                </div>
                {/* Form End */}
            </div>
            <Footer />
        </div>
    )
}

export default Login