import { AuthLink, Input, Button } from "@components/atoms";
import { Form, Footer } from "@components/molecules";
import Head from "next/head"

function Register() {
    return (
        <div className="h-full bg-primary text-white flex flex-col">
            <Head>
                <title>Toqcer | Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex-1 flex flex-col items-center">
                <h1 className="text-orange font-bold text-4xl my-14">ToqCer</h1>
                {/* Form */}
                <div className="max-w-xl w-full">
                    <Form title="Sign Up">
                        <Input
                            label="name"
                            placeholder="Name"
                            type="text"
                            required />
                        <Input
                            label="email"
                            placeholder="Email"
                            type="email"
                            required />
                        <Input
                            label="password"
                            placeholder="Password"
                            type="password"
                            required />
                        <Button>Sign in</Button>
                    </Form>
                    <div className="flex justify-between text-sm px-2 py-3 text-muted ">

                        <AuthLink href="/login" title="Sign in" />
                    </div>
                </div>
                {/* Form End */}
            </div>
            <Footer />
        </div>
    )
}

export default Register